# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.define "master1" do |master1|
    master1.vm.box = "ubuntu/xenial64"
    master1.vm.provision "file", source: "supplimentary", destination: "/usr/setup"
    master1.vm.provision "shell", inline: <<-SHELL
      /usr/setup/setup.sh master1
    SHELL
  end

  config.vm.define "master2" do |master2|
    master2.vm.box = "ubuntu/xenial64"
    master2.vm.provision "file", source: "supplimentary", destination: "/usr/setup"
    master2.vm.provision "shell", inline: <<-SHELL
      /usr/setup/setup.sh master2
    SHELL
  end

  config.vm.define "node1" do |node1|
    node1.vm.box = "ubuntu/xenial64"
    node1.vm.provision "file", source: "supplimentary", destination: "/usr/setup"
    node1.vm.provision "shell", inline: <<-SHELL
      /usr/setup/setup.sh node
    SHELL
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "ubuntu/xenial64"
    node2.vm.provision "file", source: "supplimentary", destination: "/usr/setup"
    node2.vm.provision "shell", inline: <<-SHELL
      /usr/setup/setup.sh node
    SHELL
  end

  config.vm.define "node3" do |node3|
    node3.vm.box = "ubuntu/xenial64"
    node3.vm.provision "file", source: "supplimentary", destination: "/usr/setup"
    node3.vm.provision "shell", inline: <<-SHELL
      /usr/setup/setup.sh node
    SHELL
  end

#   config.vm.define "node4" do |node4|
#     node4.vm.box = "ubuntu/xenial64"
#     node4.vm.provision "file", source: "supplimentary", destination: "/usr/setup"
#     node4.vm.provision "shell", inline: <<-SHELL
#       /usr/setup/setup.sh node
#     SHELL
#   end
# 
#   config.vm.define "node5" do |node5|
#     node5.vm.box = "ubuntu/xenial64"
#     node5.vm.provision "file", source: "supplimentary", destination: "/usr/setup"
#     node5.vm.provision "shell", inline: <<-SHELL
#       /usr/setup/setup.sh node
#     SHELL
#   end
# 
#   config.vm.define "node6" do |node6|
#     node6.vm.box = "ubuntu/xenial64"
#     node6.vm.provision "file", source: "supplimentary", destination: "/usr/setup"
#     node6.vm.provision "shell", inline: <<-SHELL
#       /usr/setup/setup.sh node
#     SHELL
#   end

  config.vm.define "client" do |client|
    client.vm.box = "ubuntu/xenial64"
    client.vm.provision "file", source: "supplimentary", destination: "/usr/setup"
    client.vm.provision "shell", inline: <<-SHELL
      /usr/setup/setup.sh client
    SHELL
  end
end
